### ISSUE TITLE
Display issue when displaying WebView

### ISSUE THREAD

**Issue by fvisticot** [bnxm/sliding-sheet#28]
I display a WebView in the sliding-sheet and sometimes I get displaying mistakes when navigating from 1 Web page to another (previous page elements seems to persist)

If you take a look on the video, you see a persistent grey box leaving from the last page.

This issue is not visible if I use the flutter web view without the sliding sheet

![weview](https://user-images.githubusercontent.com/153679/79143036-c9baaf00-7dbc-11ea-9b21-34086bda5d75.gif)

**Comment by BendixMa** [comment]
I haven't tried using a WebView inside a sliding sheet yet and have no idea why this grey box to stays there. 

I'll try to reproduce this error and see what I can do, however as I already said I'm quite busy myself right now so it might take a while...
