### ISSUE TITLE
How to scrollTo maxScrollExtent on the slidesheet

### ISSUE THREAD

**Issue by heshaShawky** [bnxm/sliding-sheet#31]
I'm building a comments sheet and I wanna the user after his adding the comment the app scrolls down automatically to the `maxScrollExtent`  

I found the method `SheetController.of(context).scrollTo()` but I can't figure out how to get the last offset on the sheet `maxScrollExtent`.

I found only `state.maxExtent` but it returns 1.0 only!

**Comment by bnxm** [comment]
Hey thanks for the issue. I haven't thought about that one actually. I'll add this property to the `SheetState` class in the next release.  

What you might wanna try out for now is simply putting a very high value into the `scrollTo` method. I think the `Scrollable` should clip the value to the `maxScrollExtent`.

The `state.extent` represents the extent that the sheet covers relative to its available space.

**Comment by heshaShawky** [comment]
When you update the repo on GitHub, please reply here so I can update the package from the repo directly instead of waiting to pub.dev

**Comment by bnxm** [comment]
Say when you have an empty scaffold without an `AppBar` and the sheet is halfway open, than this value would be 0.5. 1.0 would mean the sheet is taking up all its available space (the whole screen in this case) and would begin to scroll if the content is bigger than the screen size.

**Comment by bnxm** [comment]
The `SheetState` has this field in version 0.3.5 now included.

**Comment by heshaShawky** [comment]
> The `SheetState` has this field in version 0.3.5 now included.

Thanks a lot, I have checked out and it's working amazingly.
