### ISSUE TITLE
Adding SafeArea when setting addTopViewPaddingOnFullscreen to true

### ISSUE THREAD

**Issue by fvisticot** [bnxm/sliding-sheet#33]
When addTopViewPaddingOnFullscreen is set to true, how to take into account the SafeArea.
Is it possible ?
When the panel is fullScreen we need to take into account the notch with SafeArea or equivalent

**Comment by bnxm** [comment]
The sheet uses `MediaQuery.of(context).viewPadding.top` to determine the top padding which, according to the docs, should have any notches already included. Alas, I have no phone with a notch so I am not able to test what you mean.
