### ISSUE TITLE
initial snap position

### ISSUE THREAD

**Issue by brizaldi** [bnxm/sliding-sheet#34]
is there a way to set initial/default snap position to some extent? for example i want my sheet to fully opened when user open my app

**Comment by bnxm** [comment]
No, not yet but I will add it into one of the next releases. 

For now you could animate the sheet with a duration of 0 using the `SheetController` after short delay.

**Comment by bnxm** [comment]
The `SnapSpec` has this option in version 0.3.5 now included.

**Comment by brizaldi** [comment]
thank you for the quick update, will try it
