### ISSUE TITLE
SheetController not working with the listener

### ISSUE THREAD

**Issue by heshaShawky** [bnxm/sliding-sheet#36]
I tried to listen to the state by using the listener inside the `SlidingSheetDialog` and do something like scrolling to the maxScrollExtent but not working throwing an error `scrollTo(xxx) on null`. 

My code:
```dart
showSlidingBottomSheet(context, builder: (BuildContext context) {
  return SlidingSheetDialog(
    //...
    listener: (state) {
     // not working 
     if (state.isExpanded) {
        SheetController.of(context).scrollTo(state.maxScrollExtent);
      }
    },
   // ...
  };
}
```

**Comment by bnxm** [comment]
Yes but this is to be expected. You are using a `BuildContext` that is above the `SlidingSheet` in the widget tree. You would need to assign a `SheetController` directly:

```
final controller = SheetController();

showSlidingBottomSheet​(context, builder​:​ (​BuildContext​ context) {
  ​return​ ​SlidingSheetDialog​(
    controller: controller,
    ​//...​
    listener​:​ (state) {
     ​// not working ​
     ​if​ (state.isExpanded) {
        ​controller.scrollTo(state.maxScrollExtent);
      }
    },
   ​// ...​
  };
}
```

Note however, that the listener also gets called when the sheet scrolls, so you might wanna add some further checks before always calling `controller.scrollTo(state.maxScrollExtent)`.
