### ISSUE TITLE
A white Row at the Top of the bottomSheet

### ISSUE THREAD

**Issue by gopikm** [bnxm/sliding-sheet#44]
![photo_2020-06-24 16 43 50](https://user-images.githubusercontent.com/7264699/85545817-ed5e6900-b639-11ea-8670-edbe60f8b258.jpeg)

**Comment by gopikm** [comment]
Looks like its the border between the header and the body

**Comment by bnxm** [comment]
Yea I'll release a new version soon that should fix this. Did you set a color on the sheet? When you set the color on the sheet to be the same as for your content this shouldn't be visible.
